### ISSUE TITLE
Check if there is really a dependency to org.junit by EGradle main

### ISSUE THREAD

**Issue by de-jcup** [de-jcup/eclipse-jenkins-editor#13]
From eclipse market place:

> Cannot complete the install because one or more required items could not be found. Software being installed: Jenkins Editor 0.3.0 (de.jcup.jenkinseditor.feature.feature.group 0.3.0) Missing requirement: EGradle 2.2.1 (de.jcup.egradle.eclipse.plugin.main 2.2.1) requires 'bundle org.junit 0.0.0' but it could not be found Cannot satisfy dependency: From: Jenkins Editor 0.3.0 (de.jcup.jenkinseditor.feature.feature.group 0.3.0) To: de.jcup.egradle.eclipse.plugin.main [2.2.1]

a little bit odd - normally the main plugin should have no dependency to org.junit

**Comment by paulvi** [comment]
This is issues of EGradle actually

**Comment by de-jcup** [comment]
When Version 0.4.0 is deployed - with dependency to EGradle main 2.3.0 - this should be fixed. The issue is now only to check if the problem no longer occurs on marketplace for jenkins-editor... (because not appearing at egradle marketplace site)
