### ISSUE TITLE
[minor] Error in Jenkins file should not be the project error

### ISSUE THREAD

**Issue by paulvi** [de-jcup/eclipse-jenkins-editor#16]
in https://github.com/de-jcup/eclipse-jenkins-editor/issues/3#issuecomment-340946593

error is shown as project error, but I think any error in `.Jenkinsfile` or any `*.sh` file should not set project status as error, and make Eclipse ask "Errors are in the project. Continue running Yes|No".

This however is question what is defined as project part.

![](https://user-images.githubusercontent.com/11644753/32255037-50ba4c06-bea5-11e7-9fc8-87e290a7ab21.png)

**Comment by de-jcup** [comment]
![grafik](https://user-images.githubusercontent.com/11644753/32289974-ce04e642-bf38-11e7-816e-72670e80b2c9.png)

Hm... every error occuring inside a project does result in such action when eclipse is configured as shown in picture above. But you are always able to delete the error inside problem view... Or just fix the script and validate again (will remove the error marker).

Would you prefer it to be a `Warning` instead?

**Comment by paulvi** [comment]
I guess it be possible to configure if user prefers error or just warning.

But this is minor

**Comment by de-jcup** [comment]
Will be done like on bash editor where error levels are configurable. But needs also changes in egradle marker support class
