### ISSUE TITLE
[minor] Nondeclarative script breaks outline

### ISSUE THREAD

**Issue by paulvi** [de-jcup/eclipse-jenkins-editor#20]
There's great collections of examples at https://github.com/jenkinsci/pipeline-examples

and `nodejs-build-test-deploy-docker-notify\Jenkinsfile` there has `#!groovy`, that breaks Outline tree

**Comment by paulvi** [comment]
Everything else works great.

**Comment by de-jcup** [comment]
For https://github.com/jenkinsci/pipeline-examples/blob/6f1f8770304d25b1f02ad97170bb917982f2c33a/jenkinsfile-examples/nodejs-build-test-deploy-docker-notify/Jenkinsfile

It is not the #!groovy which makes the problems but the missing {} and also the try-catch block in combination.

Must be fixed in EGradle so closing this issue. here.

**Comment by de-jcup** [comment]
reopened issue to keep this as alive and mentioned in milestone etc.

**Comment by de-jcup** [comment]
This will not be fixed inside EGradle, see https://github.com/de-jcup/egradle/issues/321 for reasons.

Maybe inside the jenkins editor it makes sense, but not in normal groovy outline.

**Comment by de-jcup** [comment]
@paulvi . The mentioned script is non declarative but only plain script code (as shown in  de-jcup/egradle#321 ): 
![image](https://user-images.githubusercontent.com/11644753/32613416-27b2b3e4-c56b-11e7-8863-9003e640fac1.png)


 It would be possible to handle this in JenkinsEditor-Outline different. 

But I would not feel comfortable about it . What kind of expressions should be recognized inside outline and which not?

For example:
try,catch - which icon ? or should ignore in try
stage - as expression!?!?
...

In my opionion the editor should support declarative syntax only.

**Comment by paulvi** [comment]
I suggest just leave it as it is.
