### ISSUE TITLE
Documentation updates

### ISSUE THREAD

**Issue by de-jcup** [de-jcup/eclipse-jenkins-editor#21]
- [ ] document issue about supporting only declarativew way in outline - see #20 for details

**Comment by paulvi** [comment]
Like

This plugin focuses on supporting only [declarative pipeline](https://jenkins.io/doc/book/pipeline/syntax/) in outline.  
For scripted pipeline external help is needed. Currently known issues list is as follows:  
1. https://github.com/de-jcup/egradle/issues/321 Try-Catch-Block and closures without { are breaking outline

**Comment by de-jcup** [comment]
Documentation about declarative pipelines done in
- https://github.com/de-jcup/eclipse-jenkins-editor/wiki/FAQ
- https://github.com/de-jcup/eclipse-jenkins-editor/wiki/Outline
