### ISSUE TITLE
Space vs Tab Option

### ISSUE THREAD

**Issue by botPotyo** [de-jcup/eclipse-jenkins-editor#22]
Would it be possible to add an option to use spaces (and number of spaces)  instead of tabs in the editor?

**Comment by paulvi** [comment]
use Eclipse preferences for all TextEditor-based editors

![image](https://user-images.githubusercontent.com/1614482/32927851-ef46f216-cb89-11e7-9b02-6e720ac41ebf.png)

**Comment by de-jcup** [comment]
@paulvi  thank you for the answer - absolute correct.
When enabling "Insert spaces for tabs" as described by paul in picture above this works: When opening Jenkinseditor 0.4.0 and entering `a + TAB + b +TAB + c` and enabling "Show whitespcae character' you will see the tabs are replaced by spaces:

![image](https://user-images.githubusercontent.com/11644753/32946993-17b37048-cb9a-11e7-8af0-a3a5caff1f7a.png)

So I close the issue.
