### ISSUE TITLE
language server for Jenkinsfile, Groovy

### ISSUE THREAD

**Issue by paulvi** [de-jcup/eclipse-jenkins-editor#24]
With web IDE and web technologies wave there came issue how to reuse desktop IDE tech in web.
There is now Eclipse Che project - web IDE written in Java (GWT)

And recently Pivotal (company behind Spring.io ) announced next generation tooling to support Atom, Visual Studio Code as well https://spring.io/tools4

Red Hat is active in Java tools for Visual Studio Code and Java language server implementation
https://github.com/eclipse/eclipse.jdt.ls

I think what is used in Jenkinsfile Editor can be base for Groovy language server.
But of course that is big piece of work.

**Comment by paulvi** [comment]
Oh, there is already implementation https://github.com/palantir/language-servers

listed in https://microsoft.github.io/language-server-protocol/implementors/servers/

**Comment by mickaelistria** [comment]
I agree a language server for Jenkinsfile would be great. But IMO, it's more something that should be requested directly to the Jenkins project.
