### ISSUE TITLE
Scripted jenkinsfile pipelines support (Not the Declarative)

### ISSUE THREAD

**Issue by EliMutchnik** [de-jcup/eclipse-jenkins-editor#25]
Hi!
I am trying to move working on Jenkinsfiles in eclipse (from an editor) and i saw your plugin.
It looks great! I have couple of questions here:

- Does is support the Scripted form of writing jenkinsfiles (https://jenkins.io/doc/book/pipeline/syntax/#scripted-pipeline)

- How should i start using this plugin on my project? I can't quite get the what i see in the screenshots.

Thanks!

**Comment by de-jcup** [comment]
Hi @EliMutchnik ,

The outline content has some restrictions (see https://github.com/de-jcup/eclipse-jenkins-editor/wiki/Outline  for details). At the moment  outline view us supporting only declarative pipelines full.
This was also discussed earlier in https://github.com/de-jcup/eclipse-jenkins-editor/issues/20

> I can't quite get the what i see in the screenshots.

I just released version 1.0.0 at marketplace, so screenshots from wiki corresponds now correctly with released version again.

If you are using Linux there is currently a big bug with jenkins linter validation, see
https://github.com/de-jcup/eclipse-jenkins-editor/issues/27 for Details.
But I will fix it in near future.

**Comment by de-jcup** [comment]
@EliMutchnik : I fixed the linux problems and also uploaded a video to you tube which shows the usage of jenkins editor. You will find the link to YouTube at the end of Wiki page: https://github.com/de-jcup/eclipse-jenkins-editor/wiki/Validate-by-Jenkins-Linter. 

Currently I am not having the intention to provide a outline view for scripted pipelines.
IMHO the declarative way is better: 
- automatically error detection
- linter validation works (my jenkins installation did not fail on some scripted parts on lint ...)
- you can always integrate scripted parts in a script-closure as well if you need it
- more standard
- easier to understand
- more gradle like...
