### ISSUE TITLE
Linter

### ISSUE THREAD

**Issue by paulvi** [de-jcup/eclipse-jenkins-editor#3]
https://github.com/de-jcup/egradle/issues/291#issuecomment-331787626

besides Editor itslef, it may make sense in future to use use external Linter
https://jenkins.io/doc/book/pipeline/development/#linter

e.g. run it by right-clicking Run

**Comment by de-jcup** [comment]
Hmm... I wouldn't define it "Run" but more a "Validate Jenkinsfile on Server" or "Validate on Server"

There should be following work packages
- [ ] Inform about call mechanism
  see https://jenkins.io/doc/book/managing/cli/

- [ ] How to setup Jenkins CLI calling?
   **Decide wich of the following options will be used **
   ~~a) Own project property page for Jenkins (like started in de-jcup/egradle#269)
   (a little bit awful to do this for every project)~~
   b) Much more simple: Jenkins Editor preferences - global jenkins remote server setup
   ~~c) provide an embedded jenkins server/ ensure started by java -jar jenkins.war? + connect to this 
one so no setup necessary? (But this is version dependent, so maybe not working on real remote server but not on development server...)~~
- [ ] Implement Jenkins CLI Setup in eclipse 
  (see "How to setup Jenkins CLI calling?") above
- [ ] Store Jenkins CLI setup data
  How to store credentials secure?
- [ ] Execute Linter on Jenkins
- [ ] Linter-Result Outputstream fetching
- [ ] Output parsing + create error markers...

**Comment by paulvi** [comment]
Once Jenkins URL is known, jar file can be downloaded (or just use bundled one as this API is pretty much stable)

from https://jenkins.io/doc/book/managing/cli/

> Downloading the client

> The CLI client can be downloaded directly from a Jenkins master at the URL /jnlpJars/jenkins-cli.jar, in effect https://JENKINS_URL/jnlpJars/jenkins-cli.jar

> While a CLI .jar can be used against different versions of Jenkins, should any compatibility issues arise during use, please re-download the latest .jar file from the Jenkins master.

**Comment by paulvi** [comment]
Instead of calling from command line

    java -jar jenkins-cli.jar [-s JENKINS_URL] [global options...] command [command options...] [arguments...]

just call from Java code as

    hudson.cli.CLI.main(String[] args)

Trick to call when the only `public` method is `main()`

**Comment by de-jcup** [comment]
Hm... the origin source for lint mechanism can be found at
https://github.com/jenkinsci/pipeline-model-definition-plugin/blob/master/pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/DeclarativeLinterCommand.java

Interesting code is:
``` java
        String script = IOUtils.toString(stdin);

        if (script != null) {
            try {
                Converter.scriptToPipelineDef(script);
                output.add("Jenkinsfile successfully validated.");
                retVal = 0;
            } catch (Exception e) {
                output.add("Errors encountered validating Jenkinsfile:");
                retVal = 1;
                output.addAll(ModelConverterAction.errorToStrings(e));
            }
        }

```

Source of converter can be found at 
https://github.com/jenkinsci/pipeline-model-definition-plugin/blob/master/pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/Converter.groovy

So it shall be simple to execute the mechanism - at least when the dependencies are fullfilled.
I would have some concerns about all dependencies of jenkins etc - I do not want them to be inside jenkins-editor. But...

New Plugin: jenkins-linter-bridge with complete jenkins dependencies inside
Own API Interface there - usable from other plugins (jenkins-editor...) so separated by OSGI and no problems with crossing dependencies...

**Comment by paulvi** [comment]
Well, it is smarter solution.

But as Declarative and Scripted Pipeline evolve, those dependencies would need to be updated.
Contrary to calling Linter from Jenkins instance, where user has control.

If that version could be configurable, and not fixed during release of this Eclipse plugin,
then it would be superb. However will it be too complicated?

**Comment by de-jcup** [comment]
Initial linter support added with 678155a but forgot to mention in commit message...

**Comment by de-jcup** [comment]
![image](https://user-images.githubusercontent.com/11644753/32254983-e93b693e-bea4-11e7-8cde-4bd47a86c324.png)
Currently only User + API Token supported

**Comment by de-jcup** [comment]
![image](https://user-images.githubusercontent.com/11644753/32255037-50ba4c06-bea5-11e7-9fc8-87e290a7ab21.png)

**Comment by paulvi** [comment]
"Validate by Jenkins Linter" 

as Linter word has been used on https://jenkins.io/doc/book/pipeline/development/#linter

**Comment by paulvi** [comment]
from CLI `help` command list, (also visible at `%JENKINS_URL%/jenkins/cli/` )

> declarative-linter | Validate a Jenkinsfile containing a Declarative Pipeline

That is the linter is for declarative syntax only. And there's no other currently.
