### ISSUE TITLE
Improve error output 

### ISSUE THREAD

**Issue by de-jcup** [de-jcup/eclipse-jenkins-editor#33]
As described at #32 errors in linter calls do not result in error logs.
Also the exitcode, potential output done by cli (before crash) are not shown.

Also the test connection fail does not show same failure in normal "linter" action. Should be same.

This should be improved.

**Comment by jimpson** [comment]
I pulled and built your latest change for this issue and tested on my system since I'm having issues connecting to Jenkins.  The output was 

>Connection` test to 'http://test-jenkins:8080/test' was NOT successful!
>JenkinsLinterCLIResult:
>- exitCode:2 (No explaination available)
>- failureMessage:Access to Jenkins was not possible.
>Maybe credentials not valid or hostname/firewall problems.
>Please check Jenkins CLI setup in preferences
>- Output was:

When I call out to this same system using the jenkins-cli.jar and pass the same authorization tokens, I am presented with the list of commands available to that user. I do not currently have any proxy configuration settings in Eclipse (Oxygen.2 Release (4.7.2)) and I was curious if there was more information you could add to the output, like the exact command being passed to the jenkins-cli.jar file.

**Comment by de-jcup** [comment]
Hello @jimpson - please do me a favor and create another comment containing:
- which version of jenkins-cli.jar do you use exaclty?
- your exact commandline call using jenkins-cli.jar
- your exact commandline output by direct usage of jenkins-cli.jar

I am currently very busy and this would maybe safe time... 
Thank you

**Comment by jimpson** [comment]
Jenkins CLI Version: 
2.89.4

Commandline Call: 
\>java -jar jenkins-cli.jar -s http://test-jenkins:8080/test -auth user:token -http declarative-linter < jenkinsfile
 
Commandline output:
Jenkinsfile successfully validated.

as a workaround until I found your plugin, I was using the following setup in gradle

>task lintJenkins(type: JavaExec) {
>	group = 'Lint'
>	description = 'Linter for Jenkinsfile'
>	main = '-jar'
>	args = ['c:/tools/jenkins-cli.jar','-s', 'http://test-jenkins:8080/test', '-http', '-auth', 'user:token', 'declarative-linter']
>	standardInput = new ByteArrayInputStream((project.file('jenkinsfile').getText()).getBytes())
>}

oddly, running the Gradle command still works on the machine in question

**Comment by de-jcup** [comment]
I added the missing error stream output to content... The dialog is now changed to eclipse standard error dialog. Details can now be found when pressing `<<Details` button:
![image](https://user-images.githubusercontent.com/11644753/37246721-3328fc58-24af-11e8-8724-f8309a2b581f.png)

**Comment by de-jcup** [comment]
@jimpson This should do the trick and give you all necessary output. If you have still problems to connect, please create a new issue for the problem.

I close now this issue, because all relevant problem information should be prompted now.
