### ISSUE TITLE
Highlight Tasks ("TODO" and "FIXME")

### ISSUE THREAD

**Issue by famod** [de-jcup/eclipse-jenkins-editor#37]
Just like in Java code.

PS: Preferences -> General -> Editors -> Structured Text Editors -> Task Tags does not work.

**Comment by de-jcup** [comment]
I will try to integrate it in next release.

**Comment by de-jcup** [comment]
Just for documentation: 

![image](https://user-images.githubusercontent.com/11644753/46345911-94b99200-c646-11e8-96e4-5cb59bf2751f.png)

![image](https://user-images.githubusercontent.com/11644753/46345957-b9ae0500-c646-11e8-8f6c-cbda23900ae1.png)

**Comment by famod** [comment]
Great, thanks!
