### ISSUE TITLE
Use Gradle 4.2?

### ISSUE THREAD

**Issue by paulvi** [de-jcup/eclipse-jenkins-editor#4]
Use Gradle 4.2? It should have some refinements

**Comment by de-jcup** [comment]
@paulvi  as marked in #6 I currently do not use gradle for building this plugin. Maybe later for dedicated tests on jenkinsfiles handlings (e.g. linter call etc.)

But why should use gradle 4.2. exactly? Sorry, I didn't catched the reason.

**Comment by paulvi** [comment]
closing.

first should be automatic build #6 with any version
