### ISSUE TITLE
Support shell parameter expansion when 'Auto create ending brackets' is activated

### ISSUE THREAD

**Issue by alexandre-fabra** [de-jcup/eclipse-jenkins-editor#53]
When the option _Auto create ending brackets_ is activated, it should not automatically create an ending bracket block with new lines if the user is actually expanding a shell variable (e.g. **${foo}**). In other words, if an opening bracket is preceded by a dollar sign (**$**), then the closing bracket should be just next to it.

Current behavior:
```
${

}
```

Expected behaviour:
```
${}
```

**Comment by de-jcup** [comment]
Hello @alexandre-fabra ,
interesting,  Currently I am a little bit busy with Asciidoctor Editor but when I have time for Jenkins and EGradle Editor again, I I will give it a try .

**Comment by BeckerFrank** [comment]
I can offer a patch for this request after pull request https://github.com/de-jcup/egradle/pull/390 is in place.

**Comment by de-jcup** [comment]
Just as an info @BeckerFrank PR has been merged yesterday

**Comment by BeckerFrank** [comment]
I did a little more cleanup on my change and have the following questions.
The BracketInsertionCompleter is implemented in eGradle plugin.
1) should we change the ${  only for the JenkinsEditor?
2) should we use the existing EditorAutoCreateEndBracketsEnabled preference or do you want to have a new preference for this.

The fix will be in class de.jcup.egradle.eclipse.ui.GroovyBracketInsertionCompleter

**Comment by de-jcup** [comment]
@BeckerFrank thank you for the questions. Here my thoughts
1. I think there is no need to an additional preference key
2. I think we should change this for all groovy stuff,

Reason:  The behaviour should be always like wanted by @alexandre-fabra - no matter if it is for a groovy part/gradle or inside Jenkins editor. 

So: 
`${` should never be treated as a closure beginning

I created https://github.com/de-jcup/egradle/issues/402 for this. @BeckerFrank if you fix this for EGradle, I will integrate next EGradle release into next Jenkins-Editor release which will fix this.

**Comment by de-jcup** [comment]
@BeckerFrank : I just released jenkins editor v1.10.0 on eclipse market place. It contains your changes from egradle so it has been fixed now.
