### ISSUE TITLE
Can we have offline installation zip file for this Eclipse-Jenkinsfile_Editor ?

### ISSUE THREAD

**Issue by PrasadNutalapati** [de-jcup/eclipse-jenkins-editor#59]
Due to our corporate regulations, it is always failing to connect to Eclipse market place. Is it possible to provide the zip version of this plugin site? So that I can install it from local ?

**Comment by de-jcup** [comment]
Hello @PrasadNutalapati , this was already described in #54 . I close this issue as a duplicate.
If there are problems, please comment at #54.
