### ISSUE TITLE
Automatic Build

### ISSUE THREAD

**Issue by paulvi** [de-jcup/eclipse-jenkins-editor#6]
How to launch build (including update site)?

I tried `gradlew` and `gradlew build`

please add section in README

**Comment by de-jcup** [comment]
Hello @paulvi . I will update the readme.md but you just have to ignore the gradle parts. like in 
https://github.com/de-jcup/egradle/issues/84
described I stil have got problems to build eclipse plugins with gradle. There is always some dependency missing etc. In EGradle I only build /src/main/java but not /src/main/java-eclipse with gradle, so at least I can test and build the not-eclipse parts. 

Inside bash editor plugin I wrote some test for bash parts and did gradle + travis as well, for Jenkins Editor currently no dedicated tests exists. So you can currently Ignore gradle completeley inside this project.

So I just have to do the old school approach: 
- feature
- plugin
- update-site
  site.xml

Open site.xml with eclipse site editor select the feature and press "Build" button... thats all.

**Comment by paulvi** [comment]
Could you reopen this?

**Comment by de-jcup** [comment]
I fixed the gradle build, so it can "cleanEclipse eclipse" works now. Also project parts without eclipse are build and tested by travis now.

**Comment by paulvi** [comment]
great
