### ISSUE TITLE
Don't add closing brakes if within string

### ISSUE THREAD

**Issue by ChristianLutz** [de-jcup/eclipse-jenkins-editor#60]
Hello,

If you you have a string like `"Hello"` and now you will just add a variable like `"Hello ${world}"` 
The editor immediately adds two lines later the closing bracket when if typed `{`

kind regards
Christian

**Comment by de-jcup** [comment]
Hello Christian,

I am myself sometimes annoyed about this "feature". Currently I am very busy and will not have time to implement a "its inside a string" handling.

But... you can disable auto bracket closing in first preference page of jenkins editor. At least It works 4 me...

**Comment by BeckerFrank** [comment]
I have a fix for this but this is in de.jcup.egradle.eclipse.ui.GroovyBracketInsertionCompleter.

**Comment by de-jcup** [comment]
Just released v1.9.1 on eclipse marketplace - contains bugfix from @BeckerFrank  inside EGradle library.
