### ISSUE TITLE
Use whitespace settings from eclipse

### ISSUE THREAD

**Issue by ChristianLutz** [de-jcup/eclipse-jenkins-editor#61]
Hello,

we use a lot of taps instead of spaces. So we have disabled the eclipse settings `Use spaces instead of tabs`. But the jenkins-editor uses usally 4 spaces.

Kind regards
Christian

**Comment by de-jcup** [comment]
Sorry for late repsonse.

I tried out and it works very well on my 2018-12 development instance and have not defined problem, as shown in next picture:

![image](https://user-images.githubusercontent.com/11644753/64375041-5500e480-d025-11e9-89bb-7b63bfdbfffd.png)

So ... it works... and I close the issue.

**Comment by ChristianLutz** [comment]
Hello @de-jcup 
Yes you're right I couldn't reproduce it either. Sorry for the noice.
And thank you
Christian

**Comment by de-jcup** [comment]
No problem - you are wellcome
