### ISSUE TITLE
Support "*Jenkinsfile*"  in file association 

### ISSUE THREAD

**Issue by Coldplayer001** [de-jcup/eclipse-jenkins-editor#64]
It will be useful for pipeline automation with Jenkins integration.

Example: 

<img width="590" alt="Capture d’écran 2019-06-26 à 20 51 20" src="https://user-images.githubusercontent.com/34127131/60233207-3d9ec180-9854-11e9-887e-3cccdec8d837.png">

Script Path : Jenkinsfile_$JOB_NAME

**Comment by de-jcup** [comment]
It's problematic to handle files without file ending in eclipse editors. Either it is an explicit name (like "Jenkinsfile" or something with a specific fileending.

But Jenkinseditor does not only support "Jenkinsfile" but also "*.jenkinsfile" and "*.jenkins"
see https://github.com/de-jcup/eclipse-jenkins-editor/wiki/FAQ#using-jenkins-or-jenkinsfile-as-file-extension, so just rename the files to have a supported file ending - e.g. "Jenkinsfile_$JOB_NAME.jenkins" and it should work out of the box.
