### ISSUE TITLE
Gstring highlighting 

### ISSUE THREAD

**Issue by pipeti** [de-jcup/eclipse-jenkins-editor#67]
Hi,

I get inconsistent highlighting, when using a triple-double-quoted limited gstring, e.g.:

```groovy
def testScript() {
        return sh (
        script:
        """
        #!/bin/bash
        echo "This is a test script!"
        """,
        returnStatus: false,
        returnStdout: true
        ).trim()
    }
```

The coloring is not exactly consistent, seems the string is terminated by the single-double-quote and then a new one is started by the other one.
![string_syntax](https://user-images.githubusercontent.com/5348398/65308609-bb8c1380-db8a-11e9-9cb0-724f6ca069a9.PNG)

Any recommendations?
Thanks

**Comment by de-jcup** [comment]
Hi. Seems multi line string is accidently terminated here on syntax highlighting. Is now marked as a bug. 
Must be fixed inside EGradle Editor, because used internally by Jenkins Editor as library.

**Comment by sebthom** [comment]
@de-jcup The last commit to this repo is a year ago. Any chance this issue will get resolved eventually or is development stopped?

**Comment by Grummel7** [comment]
It's the same with triple single-quotes and can be quite annoying.
I stumbled upon it when using script like this:
'''
sed 's/something//' file
...
'''

Since the editor thought the s/something// was outside the quoted string, it treated the // as a comment and so skipped over the closing quote. As a consequence, the quote detection was broken for the rest of the file.

**Comment by de-jcup** [comment]
Must be fixed inside EGradle before - see mentioned link. EGradle editor is internally used in Jenkins Editor as base

**Comment by de-jcup** [comment]
With jenkins editor 1.8.0 I got

![image](https://user-images.githubusercontent.com/11644753/148793067-9e57ce15-6461-48d7-a4f6-14062fa5a7af.png)

and also
![image](https://user-images.githubusercontent.com/11644753/148793160-4168d8e8-975d-4d81-a3c9-2f8307a74e86.png)

So it looks fine for myself - so I close this issue. If this is still a problem please comment at this issue and add some explicit example snippets.
