### ISSUE TITLE
Jenkins Editor to strict with autocomple.

### ISSUE THREAD

**Issue by midikem** [de-jcup/eclipse-jenkins-editor#69]
Oki so I want to extract for example the stage part to a method. If I start writing my method in Jenkinsfile like this and I want the s to autocomple to stage, but the only word i can write here is pipeline. Conclusion is that the Jenkins Editor is way to strict compared to what you actually can do with Jenkinsfiles. It should autocomple all possible s names if i write s that is valid for a Jenkinsfile. So for example stages,stage,step and script tag should be visible if I try to autocomple s even if its not in the correct structure of Jenkinsfile. Because everything could potentially be extracted to a library or a method. 

def test() {
	return s       
}

**Comment by de-jcup** [comment]
Hello @midikem ,

i have tried out to provide additional DSL proposals - no matter if its in correct context or not.
These proposals will always start with a warn icon:

![image](https://user-images.githubusercontent.com/11644753/66395126-f689a600-e9d6-11e9-82df-bf243173cc57.png)

Every wellknown DSL part (by jenkins editor...) is contained.

Would this help you?

**Comment by midikem** [comment]
Oh yes that would be really awesome. Exactly that functionality I want. Then you can do stuff like this with auto completion.

def myFunction() {
  return {
    stage("tada") {
      println "tada" 
    }
  }
}

and then in real pipeline script call for that like this myFunction().call() It could also then be part of shared-groovy lib and be called for as above.

**Comment by de-jcup** [comment]
Per default the strict mode will be active, but you can change inside preference (last checkbox - see next figure) "Show also NON strict code proposals"

![image](https://user-images.githubusercontent.com/11644753/109403317-c391da80-795c-11eb-8de0-b2931e272eef.png)
