### ISSUE TITLE
How to set tabs to use spaces

### ISSUE THREAD

**Issue by gurcei** [de-jcup/eclipse-jenkins-editor#70]
While editing my Jenkinsfile, I've noticed that tabs use the tab character. I'd prefer to use 4 spaces, as that's the preference across our team, but I'm unsure where to set this preference.

**Comment by de-jcup** [comment]
The editor uses the default text editor settings, so just do 

`Window -> Preferences` enter "tab" in search field. After this just enable "Insert spaces for tabs" and you are done.

![image](https://user-images.githubusercontent.com/11644753/77375187-07538b80-6d6d-11ea-8009-bf4a68dd30ee.png)
