### ISSUE TITLE
"unsucessful" post block is not highlighted

### ISSUE THREAD

**Issue by famod** [de-jcup/eclipse-jenkins-editor#73]
![grafik](https://user-images.githubusercontent.com/22860528/80945472-2e7d8e00-8dec-11ea-9066-ff2e17a87a9e.png)

"unsucessful" is not in bold red, unlike .e.g "always" etc.

**Comment by de-jcup** [comment]
Here a snippet as test code to check highlighting after change:

```gradle
post {
  unsuccessful {
        echo "something"
  }
}
