### ISSUE TITLE
Jenkinsfile editor does not store the credentials from the settings for me

### ISSUE THREAD

**Issue by chriskloe** [de-jcup/eclipse-jenkins-editor#77]
Every time I want to make use of jenkinsfile linter I am getting this error: 'Jenkins CLI call failed' with these details:
`Jenkins CLI call failed.
JenkinsLinterCLIResult:
- exitCode:-2 (Linter was not executed at all)
- failureMessage:Access to Jenkins was not possible by command:

java -jar C:\Apps\jenkins-cli\jenkins-cli.jar -s http://%JENKINS_SERVER%:8080 -http -noCertificateCheck -auth null:******* declarative-linter 

Maybe credentials not valid or hostname/firewall problems.
Please check Jenkins CLI setup in preferences
-Output was:
`
(URL obfuscated), no matter how often I set the right credentials in the setting dialog.

When I copy the command to a commandline and replace 'null:*****' with my actual credentials, then paste a jenkinsfile to the console, it works. So it's not a matter of the server-URL, a missing jenkins-cli.jar, missing or wrong java but instead only of jenkinsfile-editor not storing credentials in the settings or reading wrong credentials out of the settings.

My versions:
- Jenkins: 2.249.2 (LTS) on Windows server
- Eclipse: 2020-09 on Windows 10
- jenkinsfile-editor 1.7.0
- Java: OpenJDK 11.0.6 (Azure Java) (Due to licence policy, my company moved away from Oracle Java)

**Comment by chriskloe** [comment]
It's still failling for eclipse 2021-3 and jenkins 2.277.3

**Comment by chriskloe** [comment]
Thank you very much!
Since the last update I noticed some modifications and extended error messages around my issue but the issue still is there:
when I enter my credentials to the settings, I can test the connection succecssfully, but the button "Apply and Close" does not do anything, the window stays open. When I push "Apply" only and then "Cancel", the settings are not stored. Whem I come back to the settings and want to test the connectinos it fails with missing credentials.
Does that help? Please come back to me if you need more detailled description. I could also create a windows problem description if that feature is still available in windows 10.

Best regards,
Christoph

**Comment by de-jcup** [comment]
I tried out now following:
- Windows10 
- Fresh Eclipse 2021-03
- Installed Jenkins Editor Plugin v1.8.0 from eclipse marketplace
- started a Jenkins at Linux VM (bridged network mode, temporary host IP - I call it here `${hostIp}`  with 
```bash
#!/bin/bash
# https://github.com/jenkinsci/docker/blob/master/README.md
sudo docker run -p 8080:8080 -p 50000:50000 -v jenkins_home:/var/jenkins_home jenkins/jenkins:lts
```
(at the moment this  does start a Jenkins 2.277.4 )
- After docker image has been started I opened https:/${hostIp}:8080 on my windows machine
 and finished the installation of jenkins with suggested  plugins and create user `albert`.

- Then I created a http://${hostIp}:8080/user/albert/conifgure a new API token for my user , remembered it, and saved the page

Than I configured at my windows machine inside the preferences
![image](https://user-images.githubusercontent.com/11644753/117328029-85042900-ae93-11eb-83d4-40a836cb47c8.png)


- I pressed the button "credentials", typed "albert" (my username ) and entered the remembered token
- I pressed "Test connection" button - worked
- I pressed "Apply and Close" button
- I created a new file called it `test.jenkins`,opened it and  entered some pipeline code there 
- I pressed the Linter button at the main toolbar and got a resulting message from Jenkins

So it worked out-of-the-box.

@chriskloe : Please do me a favor and try following:

- try those steps at your own environment and check out if this works.
- if there are still issues check inside the error log view for more details and provide them

**Comment by chriskloe** [comment]
The notification e-Mail I got first had a slightly different content?!
OK, on my installation: every time I push that "Apply and Change" button in the setting, simply noting happens. If I push "Apply", switch to another settings pane, come back and push "Test Connection", it does not work. When I enter the credentials settings again, these are empty.
I have another eclipse installation in a VM, let me check there... it's an 2021-3 as well but yet without checked out jenkinsfiles and jenkinsfile editor.
Yes, "Apply and Close" does close the windows there and I can lint the files successfully there!
Any idea how to  fix the secure storage issue?
I'll start a google session and keep you updated. Thanks so far!

**Comment by chriskloe** [comment]
Back again.
I wanted to start removing unused entries from my secure storage but in fact the button cleaned my total content. 
But the positive side: it works now!
Great, thank you very much again!

**Comment by de-jcup** [comment]
> The notification e-Mail I got first had a slightly different content?!
> ...
@chriskloe : Just a remark why two notifications:

I updated the comment so you did get two notifications... At the beginning I wanted you to setup also a test jenkins, but after reading your issue again, it became clear that secure storage must be the problem and not a wrong jenkins setup...

So I transfered my test descriptions to wiki , linked only, and gave you are better

**Comment by de-jcup** [comment]
> Back again.
> I wanted to start removing unused entries from my secure storage but in fact the button cleaned my total content.
> But the positive side: it works now!
> Great, thank you very much again!

Yes, I had also some issues with the secure storage mechansim sometimes.
Can we close this (and the related) issues?

**Comment by chriskloe** [comment]
Yes, thanks again!
