### ISSUE TITLE
Move plugin update-site to another location (bintray is in sundown)

### ISSUE THREAD

**Issue by de-jcup** [de-jcup/eclipse-jenkins-editor#78]
Because of bintray sundown - see https://github.com/de-jcup/eclipse-asciidoctor-editor/issues/333 for details - the plugin must be hosted somewhere else.

Will include
- new infrastructure
- change update site location
- change way of deployment - remove old bintray auto deploy script

With https://github.com/de-jcup/p2-updatesite-github-pages-automation/issues/1  there is now a dedicated repository which shall be the base for bugfixes, enhancements etc. related to the new `deploy.sh `script

**Comment by ebramirez** [comment]
Hi @de-jcup,

Is is this comming along?
The update site is no longer responding.

**Comment by robertschulze** [comment]
I have the same problem, the plugin cannot be installed.

**Comment by de-jcup** [comment]
I just tested - and the plugin is no longer hosted at https://bintray.com/de-jcup only 3 repositories are listed: `yamleditor`, `sqleditor`, `test-generic` but not this one.

OMG. I have no idea why this happened - it seems this is an issue at bintray. 
Nevertheless I will migrate as soon as possible and provide a new update url at marketplace.

**Comment by de-jcup** [comment]
Created https://github.com/de-jcup/update-site-eclipse-jenkins-editor

**Comment by de-jcup** [comment]
Just released Version 1.8.0 on eclipse marketplace and tested installation. Works now as expected.

**Comment by ebramirez** [comment]
Thanks a lot @de-jcup!

**Comment by smartheye** [comment]
Thank you
