### ISSUE TITLE
Get listed on https://jenkins.io/doc/book/pipeline/development/

### ISSUE THREAD

**Issue by paulvi** [de-jcup/eclipse-jenkins-editor#8]
https://jenkins.io/doc/book/pipeline/development/ lists some tools, including 3rd party's

There should be a way for this plugin to be listed there.

**Comment by de-jcup** [comment]
It is possible to improve the site with editing a fork -
either by directly edit
https://github.com/jenkins-infra/jenkins.io/edit/master/content//doc/book/pipeline/development.adoc

or branch...

**Comment by de-jcup** [comment]
Did a pull request to get liseted - see  https://github.com/jenkins-infra/jenkins.io/pull/1339

**Comment by paulvi** [comment]
DONE https://jenkins.io/doc/book/pipeline/development/#eclipse-jenkins-editor
